apiVersion: v1
kind: Service
metadata:
  name: ienabs-nginx-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30040
  selector:
    app: my_nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ienabs-nginx-depl2
  labels:
    app: my_nginx
spec:
 replicas: 4
 selector:
    matchLabels:
      app: my_nginx
 template:
   metadata:
     labels:
       app: my_nginx
   spec:
     containers:
     - name: nginx
       image: nginx:1.23.1
       ports:
       - containerPort: 80
